refactored setup-runner action to install llama-stack

diff --git a/.github/actions/setup-runner/action.yml b/.github/actions/setup-runner/action.yml
--- a/.github/actions/setup-runner/action.yml
+++ b/.github/actions/setup-runner/action.yml
@@ -27,17 +27,38 @@ runs:
         echo "Installing ad-hoc dependencies"
         uv pip install faiss-cpu
 
+        # # Install llama-stack-client-python based on the client-version input
+        # if [ "${{ inputs.client-version }}" = "latest" ]; then
+        #   echo "Installing latest llama-stack-client-python from main branch"
+        #   uv pip install git+https://github.com/llamastack/llama-stack-client-python.git@main
+        # elif [ "${{ inputs.client-version }}" = "published" ]; then
+        #   echo "Installing published llama-stack-client-python from PyPI"
+        #   uv pip install llama-stack-client
+        # else
+        #   echo "Invalid client-version: ${{ inputs.client-version }}"
+        #   exit 1
+        # fi
+
+        # echo "Installed llama packages"
+        # uv pip list | grep llama
+
+
+    - name: Build Llama Stack
+      shell: bash
+      run: |
         # Install llama-stack-client-python based on the client-version input
         if [ "${{ inputs.client-version }}" = "latest" ]; then
           echo "Installing latest llama-stack-client-python from main branch"
-          uv pip install git+https://github.com/llamastack/llama-stack-client-python.git@main
+          export LLAMA_STACK_CLIENT_DIR=git+https://github.com/llamastack/llama-stack-client-python.git@main
         elif [ "${{ inputs.client-version }}" = "published" ]; then
           echo "Installing published llama-stack-client-python from PyPI"
-          uv pip install llama-stack-client
+          unset LLAMA_STACK_CLIENT_DIR
         else
           echo "Invalid client-version: ${{ inputs.client-version }}"
           exit 1
         fi
 
-        echo "Installed llama packages"
-        uv pip list | grep llama
+        echo "Building Llama Stack"
+
+        LLAMA_STACK_DIR=. \
+          uv run --no-sync llama stack build --template ci-tests --image-type venv
