adding 'remote-vllm-gpu' template

diff --git a/.github/workflows/integration-tests-on-gpu-self-hosted-runner.yaml b/.github/workflows/integration-tests-on-gpu-self-hosted-runner.yaml
--- a/.github/workflows/integration-tests-on-gpu-self-hosted-runner.yaml
+++ b/.github/workflows/integration-tests-on-gpu-self-hosted-runner.yaml
@@ -38,7 +38,8 @@ on:
 
 env:
   CONTAINER_NAME: vllm_server
-  LLAMA_STACK_TEMPLATE: ci-tests
+  LLAMA_STACK_TEMPLATE: remote-vllm-gpu
+  EMBEDDING_MODEL: sentence-transformers/all-MiniLM-L6-v2
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
@@ -72,12 +73,14 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
+
       - name: Setup vllm GPU
         uses: ./.github/actions/setup-vllm-gpu
         with:
           model: ${{ inputs.model }}
           huggingface-pat: ${{ secrets.HF_PAT }}
           vllm-container: ${{ env.CONTAINER_NAME }}
+
 
       - name: Verify VLLM remote server is healthy
         env:
@@ -111,6 +114,44 @@ jobs:
 
           exit 1
 
+
+      # - name: Build Llama Stack
+      #   run: |
+      #     uv run llama stack build --template ${{ env.LLAMA_STACK_TEMPLATE }} --image-type venv
+
+
+      # - name: Start Llama Stack server in background
+      #   # if: matrix.client-type == 'http'
+      #   env:
+      #     INFERENCE_MODEL: ${{ inputs.model }}
+      #     ENABLE_VLLM: "vllm"
+      #     VLLM_URL: "http://${{ inputs.vllm-server-ip }}:8000/v1/"
+      #     VLLM_INFERENCE_MODEL: ${{ inputs.model }}
+      #   run: |
+
+      #     LLAMA_STACK_LOG_FILE=server.log nohup uv run llama stack run \
+      #       $HOME/.llama/distributions/${{ env.LLAMA_STACK_TEMPLATE }}/${{ env.LLAMA_STACK_TEMPLATE }}-run.yaml \
+      #       --image-type venv \
+      #       --env ENABLE_VLLM=${{ env.ENABLE_VLLM }} \
+      #       --env VLLM_URL=${{ env.VLLM_URL }} \
+      #       --env VLLM_INFERENCE_MODEL=${{ env.VLLM_INFERENCE_MODEL }} &
+
+
+      # - name: Wait for Llama Stack server to be ready
+      #   # if: matrix.client-type == 'http'
+      #   run: |
+      #     echo "Waiting for Llama Stack server..."
+      #     for i in {1..30}; do
+      #       if curl -s http://localhost:8321/v1/health | grep -q "OK"; then
+      #         echo "Llama Stack server is up!"
+      #         exit 0
+      #       fi
+      #       sleep 1
+      #     done
+      #     echo "Llama Stack server failed to start"
+      #     cat server.log
+      #     exit 1
+
   test-matrix:
     runs-on: [self-hosted, linux, X64]
     needs: [discover-tests, prepare_self_hosted_runner]
@@ -118,10 +159,10 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        # test-type: ${{ fromJson(needs.discover-tests.outputs.test-type) }}
+        test-type: ${{ fromJson(needs.discover-tests.outputs.test-type) }}
         # client-type: [library, server]
         # python-version: ["3.12", "3.13"]
-        test-type: [inference]
+        # test-type: [inference]
         client-type: [server]
         python-version: ["3.13"]
         client-version: ${{ (github.event_name == 'schedule' || github.event.inputs.test-all-client-versions == 'true') && fromJSON('["published", "latest"]') || fromJSON('["latest"]') }}
@@ -145,6 +186,7 @@ jobs:
           python-version: ${{ matrix.python-version }}
           client-version: ${{ matrix.client-version }}
 
+
       - name: Check Storage and Memory Available Before Tests
         if: ${{ always() }}
         run: |
@@ -154,6 +196,7 @@ jobs:
       - name: Build Llama Stack
         run: |
           uv run llama stack build --template ${{ env.LLAMA_STACK_TEMPLATE }} --image-type venv
+
 
       - name: Run Integration Tests
         env:
@@ -180,7 +223,7 @@ jobs:
             --env ENABLE_VLLM=${{ env.ENABLE_VLLM }} \
             --env VLLM_URL=${{ env.VLLM_URL }} \
             --env VLLM_INFERENCE_MODEL=${{ env.VLLM_INFERENCE_MODEL }}  \
-            --embedding-model=sentence-transformers/all-MiniLM-L6-v2 \
+            --embedding-model=${{ env.EMBEDDING_MODEL }} \
             --color=yes \
             --capture=tee-sys | tee pytest-${{ matrix.test-type }}.log
 
@@ -188,9 +231,9 @@ jobs:
           echo "[DEBUG] End time of the test: ${end_time}"
 
           test_run_duraiton=$((end_time - start_time))
-          echo "[DEBUG] Duration of the test run : ${test_run_duraiton} seconds"
+          echo "[DEBUG] Duration of the test run: ${test_run_duraiton} seconds"
           
-          # Grabbing vLLM inference server logs for the duration of a given test run: 
+          ## Grabbing vLLM inference server logs for the duration of a given test run: 
           sudo docker logs ${{ env.CONTAINER_NAME }} --since "${test_run_duraiton}s"  > ${{ env.CONTAINER_NAME }}-logs-${{ github.run_id }}-${{ github.run_attempt }}-${{ matrix.client-type }}-${{ matrix.test-type }}-${{ matrix.python-version }}-${{ matrix.client-version }}.log
 
           cat ${{ env.CONTAINER_NAME }}-logs-${{ github.run_id }}-${{ github.run_attempt }}-${{ matrix.client-type }}-${{ matrix.test-type }}-${{ matrix.python-version }}-${{ matrix.client-version }}.log
@@ -201,6 +244,7 @@ jobs:
         run: |
           free -h
           df -h
+
 
       - name: Upload all logs to artifacts
         if: ${{ always() }}
